### ISSUE TITLE
Add images of the my website to the README 

### ISSUE THREAD

**Issue by John8790909** [John8790909/CONNECT#1]
website link: quiz-connect.netlify.app

**Comment by John8790909** [comment]
@MsterAB can you do this?

**Comment by MsterAB** [comment]
I think it’s not necessary since we’re going to put an updated video of the website. Let me know if you still want me to do it tho.

**Comment by John8790909** [comment]
Yes please do it just to make the readme look better

**Comment by John8790909** [comment]
We have a video so we don't need images
