### ISSUE TITLE
Remove the npm test section from the README

### ISSUE THREAD

**Issue by John8790909** [John8790909/CONNECT#10]
Just remove the the section that says npm test and its instructions but don't touch the Subscriptions section

**Comment by facelessfool** [comment]
Can I work on this?

**Comment by MsterAB** [comment]
Sure, any help is welcome!

**Comment by John8790909** [comment]
Great job @facelessfool !

**Comment by MsterAB** [comment]
Great

**Comment by facelessfool** [comment]
Thank you.
