### ISSUE TITLE
Add a Footer

### ISSUE THREAD

**Issue by MsterAB** [John8790909/CONNECT#21]
Adding a footer to the homepage with copyright and terms and conditions

**Comment by WathikAhmed** [comment]
Is this the hompage?
https://github.com/John8790909/CONNECT/blob/main/src/components/Home.jsx

**Comment by vonet999** [comment]
Assinged me .I can do it

**Comment by MsterAB** [comment]
> Is this the hompage?
> https://github.com/John8790909/CONNECT/blob/main/src/components/Home.jsx

Yes it is. Thank you for your help

**Comment by oneamanish** [comment]
see my pull req.

**Comment by WathikAhmed** [comment]
We can’t use HTML for this. 
Please if you could make it with a react component it would be perfect. 
Thank you!

**Comment by WathikAhmed** [comment]
Done.
See pull req here:
https://github.com/John8790909/CONNECT/pull/24
