### ISSUE TITLE
.sort(() => 0.5 - Math.random()); not returning a random array

### ISSUE THREAD

**Issue by John8790909** [John8790909/CONNECT#36]

**Comment by ishaanbedi** [comment]
Hey! 
I'd like to work on this.
Can you elaborate the issue?

**Comment by harshsinghatz** [comment]
Hey john, it seems like the logic should work. 
Maybe you can check the array 

one suggestion:
cards.map((card, i) => {
      numberOfCardsArr.push(i);
});
rather than using map for iterating, you can use forEach loop as the map will return a new array

**Comment by John8790909** [comment]
Yes @harshsinghatz I tried your suggestion, but that didn't fix the issue, turns out the problem was in the order I was calling the functions, so I just rearranged it and no it works as intended. 

But thank you for your suggestion

**Comment by John8790909** [comment]
@ishaanbedi I appreciate your kindness, but I already fixed the issue
